version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Tango@2025
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tissu-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "5000:80"
    networks:
      - tissu-net

  backend:
    build:
      context: ../tissu-master
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=db # Utilise le nom du service db
      - DB_USER=db_user
      - DB_PORT=3306 # Port interne MySQL (pas 3360)
      - DB_PASSWORD=db_user_pass
      - DB_NAME=app_db
    ports:
      - "5101:5000"
    depends_on:
      - db
    restart: always
    networks:
      - tissu-net

  frontend:
    build:
      context: ../tissu-master
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
    networks:
      - tissu-net

  grafana:
    image: grafana/grafana
    ports:
      - "8083:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - tissu-net

volumes:
  dbdata:
  grafana_data:

networks:
  tissu-net:
    driver: bridge
